version: '1'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "7880:5173"
    command: [ "npm", "run", "dev" ]
  # backend:
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7875:1010"
  #   command: [ "php", "-S", "localhost:1010", "server.php" ]
  # database: